name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # A deeper fetch is required for plugins that use Git history, like git-committers.
          fetch-depth: 0 

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      # Use the official action to set up uv
      - name: Install uv and dependencies
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      
      # The `uv sync` command installs the project dependencies from pyproject.toml
      - name: Install project dependencies with uv
        run: uv sync

      - name: Build and deploy MkDocs
        run: mkdocs gh-deploy --force
